"""Add donation migration

Revision ID: 013f65e83e2b
Revises: 3ea4dc4eef02
Create Date: 2023-11-11 13:29:20.153819

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "013f65e83e2b"
down_revision = "3ea4dc4eef02"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
