"""Add user relationship to Donation

Revision ID: 1103655b1077
Revises: 9a651ad30b4d
Create Date: 2023-11-11 18:45:10.158276

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "1103655b1077"
down_revision = "9a651ad30b4d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
