"""First migration

Revision ID: 3ea4dc4eef02
Revises: 
Create Date: 2023-11-11 13:18:32.596183

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "3ea4dc4eef02"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "charityproject",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("full_amount", sa.Integer(), nullable=True),
        sa.Column("invested_amount", sa.Integer(), nullable=True),
        sa.Column("fully_invested", sa.Boolean(), nullable=True),
        sa.Column("create_date", sa.DateTime(), nullable=True),
        sa.Column("close_date", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name="fk_donation_user_id_user"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("charityproject")
    # ### end Alembic commands ###
