"""Add user relationship to Donation

Revision ID: 9a651ad30b4d
Revises: 3a1bd507bd39
Create Date: 2023-11-11 18:39:33.466939

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "9a651ad30b4d"
down_revision = "3a1bd507bd39"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
