"""Add donation migration

Revision ID: d480ea3e77c6
Revises: 013f65e83e2b
Create Date: 2023-11-11 13:31:09.179788

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "d480ea3e77c6"
down_revision = "013f65e83e2b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
